//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEUBiblioteca
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Video
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Video()
        {
        }
        [ScaffoldColumn(false)]
        public int idvideo { get; set; }
        [DataType(DataType.Text)]
        [Required(ErrorMessage = "Necesitamos el campo requerido"), MaxLength(50)]
        [Display(Name = "Título")]
        public string titulo { get; set; }
        [DataType(DataType.Text)]
        [Required(ErrorMessage = "Necesitamos una fecha")]
        [Display(Name = "Fecha de Publicación")]
        public Nullable<System.DateTime> fecha_publicacion { get; set; }
        [DataType(DataType.Text)]
        [Required(ErrorMessage = "Necesitamos el campo requerido"), MaxLength(50)]
        [Display(Name = "Formato")]
        public string formato { get; set; }
        [DataType(DataType.Time)]
        [Required(ErrorMessage = "¿Cuál es el tiempo de duración?"), MaxLength(55)]
        [Display(Name = "Duración")]
        public string duracion { get; set; }
        [DataType(DataType.Text)]
        [Required(ErrorMessage = "Necesitamos el campo requerido"), MaxLength(50)]
        [Display(Name = "Categoria")]
        public string categoria { get; set; }
    }
}
