//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEUBibliotecaa
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Libro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Libro()
        {
        }

        [ScaffoldColumn(false)]
        public int idlibro { get; set; }
        [DataType(DataType.Text)]
        [Required(ErrorMessage = "Necesitamos el título requerido"), MaxLength(55)]
        [Display(Name = "Título del Libro")]
        public string titulo { get; set; }
        [DataType(DataType.Text)]
        [Required(ErrorMessage = "Necesitamos los nombres requeridos"), MaxLength(55)]
        [Display(Name = "Autor(es) Libro")]
        public string autor { get; set; }
        [DataType(DataType.Text)]
        [Required(ErrorMessage = "Necesitamos el campo requerido"), MaxLength(55)]
        [Display(Name = "ISBN")]
        public string ISBN { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd'/'MM'/'yyyy}")]
        [Display(Name = "Fecha de Publicación")]
        public Nullable<System.DateTime> fecha_publicacion { get; set; }
        public Nullable<int> num_ejemplares { get; set; }
        [DataType(DataType.Text)]
        [Required(ErrorMessage = "Se requiere de la categoría"), MaxLength(55)]
        [Display(Name = "Categoría")]
        public string categoria { get; set; }
    }
}
